modLoader="javafml"
loaderVersion="[26,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/enderports/issues"

[[mods]]
    modId="enderports"
    version="1.0"
    displayName="Enderports"
	authors="ManApart"
    description='''
    Simple teleporter mod
    '''
    credits="Simple teleporters"

[[dependencies.lumberjack]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"